[package]
name = "allsorts"
version = "0.5.1"
authors = ["YesLogic Pty. Ltd. <info@yeslogic.com>"]
edition = "2018"

homepage = "https://github.com/yeslogic/allsorts"
documentation = "https://docs.rs/crate/allsorts"
repository = "https://github.com/yeslogic/allsorts"

readme = "README.md"
license = "Apache-2.0"
include = ["/LICENSE", "src/**/*", "benches/**/*"]

description = "Font parser, shaping engine, and subsetter for OpenType, WOFF, and WOFF2"
keywords = ["font", "shaping", "opentype", "truetype", "parse"]
categories = ["text-processing"]

[dependencies]
bitflags = { version = "1.0", default-features = false }
bitreader = { version = "0.3.2", default-features = false }
brotli-decompressor = { version = "2.3", default-features = false }
byteorder = { version = "1.2", default-features = false }
encoding_rs = { version = "0.8.27", default-features = false }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
glyph-names = { version = "0.1", default-features = false }
itertools = { version = "0.8", default-features = false }
lazy_static = { version = "1.3.0", default-features = false }
libc = { version = "0.2", default-features = false }
log = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
rental = { version = "0.5.5", default-features = false }
rustc-hash = { version = "1.1.0", default-features = false } # note: feature "std" disabled!
tinyvec = { version = "1", default-features = false, features = ["alloc"] }
ucd-trie = { version = "0.1.2", default-features = false }
unicode-general-category = { version = "0.3.0", default-features = false }
unicode-joining-type = { version = "0.5.0", default-features = false }


[dev-dependencies]
criterion = { version = "0.3", default-features = false }
regex = { version = "1.1.6", default-features = false }

[[bench]]
name = "bench-shape"
harness = false

[[bench]]
name = "bench-read"
harness = false

[features]
std = []
prince = ["std"]
default = ["std"]